### ISSUE TITLE
Error when generating headfake instance from Pyhton

### ISSUE THREAD

**Issue by anleopa** [rcfgroup/headfake#20]
> Exception has occurred: AttributeError
> 'Fieldset' object has no attribute 'get'

This error appears when executing:

```
import headfake
gender = headfake.field.GenderField(male_value="M", female_value="F", male_probability=0.5)
fs = headfake.Fieldset(fields=[gender])
hf = headfake.HeadFake.from_python(fs)
```

**Comment by rcfree** [comment]
Hi. Sorry about this. There is a mistake in the documentation.
The fieldset needs to be passed within a dictionary to the from_python method. 

e.g. 
```python
import headfake
gender = headfake.field.GenderField(male_value="M", female_value="F", male_probability=0.5)
fs = headfake.Fieldset(fields=[gender])
hf = headfake.HeadFake.from_python({"fieldset":fs})
```

This will be changed in the next update to the docs.

**Comment by anleopa** [comment]
Thank you!
